version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 2605
      PGDATA: /var/lib/postgresql/data/update

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
